name: CI-CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:20.10.16
        options: --privileged
    steps:
      - uses: actions/checkout@v3

      # Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      # Install dependencies
      - name: Install backend
        working-directory: backend
        run: npm ci

      - name: Install frontend
        working-directory: frontend
        run: npm ci

      # Build Docker images
      - name: Build backend Docker
        run: docker build -t my-backend:latest ./backend

      - name: Build frontend Docker
        run: docker build -t my-frontend:latest ./frontend

      # Run SonarQube scan
      - name: SonarQube Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          projectKey: my-app
          organization: my-org
          token: ${{ secrets.SONAR_TOKEN }}

      # Trivy security scan
      - name: Trivy Scan Backend
        run: trivy image --exit-code 1 --severity HIGH,CRITICAL my-backend:latest

      - name: Trivy Scan Frontend
        run: trivy image --exit-code 1 --severity HIGH,CRITICAL my-frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-scan
    steps:
      - uses: actions/checkout@v3

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: '1.30.0'

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/
